apiVersion: apps/v1
kind: Deployment
metadata:
  name: desxzt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desxzt
  template:
    metadata:
      labels:
        app: desxzt
    spec:
      containers:
      - image: okteto.dev/desxzt:latest
        name: desxzt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "6dcde566-cdb5-4de2-8b5e-a03962e53fed"
        - name: Vless_Path
          value: "/6dcde566-cdb5-4de2-8b5e-a03962e53fed-vless"
        - name: Vmess_UUID
          value: "6dcde566-cdb5-4de2-8b5e-a03962e53fed"
        - name: Vmess_Path
          value: "/6dcde566-cdb5-4de2-8b5e-a03962e53fed-vmess"
        - name: Share_Path
          value: "/share233"
