apiVersion: apps/v1
kind: Deployment
metadata:
  name: zsawq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zsawq
  template:
    metadata:
      labels:
        app: zsawq
    spec:
      containers:
      - image: okteto.dev/zsawq:latest
        name: zsawq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "619756a9-2300-43f7-9f7c-01db76bd3ada"
        - name: Vless_Path
          value: "/619756a9-2300-43f7-9f7c-01db76bd3ada-vless"
        - name: Vmess_UUID
          value: "619756a9-2300-43f7-9f7c-01db76bd3ada"
        - name: Vmess_Path
          value: "/619756a9-2300-43f7-9f7c-01db76bd3ada-vmess"
        - name: Share_Path
          value: "/share233"
