apiVersion: apps/v1
kind: Deployment
metadata:
  name: asxcvgtr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asxcvgtr
  template:
    metadata:
      labels:
        app: asxcvgtr
    spec:
      containers:
      - image: okteto.dev/asxcvgtr:latest
        name: asxcvgtr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "5456a4d8-9510-4210-a2e1-93efa65a537b"
        - name: Vless_Path
          value: "/5456a4d8-9510-4210-a2e1-93efa65a537b-vless"
        - name: Vmess_UUID
          value: "5456a4d8-9510-4210-a2e1-93efa65a537b"
        - name: Vmess_Path
          value: "/5456a4d8-9510-4210-a2e1-93efa65a537b-vmess"
        - name: Share_Path
          value: "/share233"
