apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmntgvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmntgvc
  template:
    metadata:
      labels:
        app: kmntgvc
    spec:
      containers:
      - image: okteto.dev/kmntgvc:latest
        name: kmntgvc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "c1f9c59d-08c2-47bf-a227-fe3999bd3161"
        - name: Vless_Path
          value: "/c1f9c59d-08c2-47bf-a227-fe3999bd3161-vless"
        - name: Vmess_UUID
          value: "c1f9c59d-08c2-47bf-a227-fe3999bd3161"
        - name: Vmess_Path
          value: "/c1f9c59d-08c2-47bf-a227-fe3999bd3161-vmess"
        - name: Share_Path
          value: "/share233"
