apiVersion: apps/v1
kind: Deployment
metadata:
  name: fgnbhy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fgnbhy
  template:
    metadata:
      labels:
        app: fgnbhy
    spec:
      containers:
      - image: okteto.dev/fgnbhy:latest
        name: fgnbhy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "060d42a6-d041-48a9-94ff-57610e999225"
        - name: Vless_Path
          value: "/060d42a6-d041-48a9-94ff-57610e999225-vless"
        - name: Vmess_UUID
          value: "060d42a6-d041-48a9-94ff-57610e999225"
        - name: Vmess_Path
          value: "/060d42a6-d041-48a9-94ff-57610e999225-vmess"
        - name: Share_Path
          value: "/share233"
